# Generated by Django 5.2.3 on 2025-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='completeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField()),
                ('projectDescription', models.TextField()),
                ('projectDate', models.DateTimeField(auto_now_add=True)),
                ('projectMedia', models.ImageField(upload_to='')),
            ],
        ),
    ]
